---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebappdeployment
spec:
  replicas: 2
  startegy:
    type: Recreate
  selector:
    matchlabels:
      app: mavenwebapp
  template:
    metadata:
      name: mavenwebapppod
      labels:
        app: mavenwebapp
    spec:
      containers:
      - name: mavenwebappcontainer
        iamge: asishdevops/mavenwebapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappsvc
spec:
  type: LoadBalancer
  selector:
    app: mavenwebapp
  ports:
    - port: 80
      targetPort: 8080
---        
